FROM php:8.1-apache

# Установка модуля mod_rewrite фтв headers
RUN a2enmod rewrite
RUN a2enmod headers
# Установка необходимых модулей PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Копирование файла .htaccess в контейнер
COPY ./src/.htaccess /usr/local/apache2/conf/

# Копирование файлов приложения в контейнер
COPY ./src /var/www/html/

